### PR TITLE
Added Code Syntax Highlighting capability to the DisplayCode component.

### PR DESCRIPTION
**Pull request by conficient**
I thought it would be interesting to see if I could enhance your excellent demo app with code syntax highlighting. I've added the **ColorCode** library to generate the syntax and modified the `<DisplayCode>` component to re-render the code samples in the given language.

Hope you like it!

### CODE REVIEW

**Comment by conficient** [comment]
A preview of how the new code sample looks:

image

**Comment by SQL-MisterMagoo** [comment]
Thanks @conficient 

I really appreciate this, there is one small issue as I see it - ColorCode doesn't seem to render CSharp well
image

Do you know if it can be tweaked to recognise Types, parameters etc?

I think I'm 98% ready to merge this, but would like to know your thoughts on the CSharp issue.

**Comment by conficient** [comment]
The issue here is the format isn't really HTML, it's Razor - which is both C# and HTML. 

I did check but Razor isn't a supported format. You could extract the C# and put it in a separate `DisplayCode` tag with the `Language='C#'` attribute - but that loses the context of the `@functions {}` part.

Another approach might be to try to split the code manually in the component, and apply both HTML and C# formatting to the separate components - that might work.

**Comment by SQL-MisterMagoo** [comment]
Yeah, I tried splitting it out - same thing - never mind - it's good enough as it is, thanks.
I'm merging, then I'll make some more changes that I have in a feature branch. 
We don't need the Cleanup - just remove the white space inside the ```<pre>``` tag, so we have ```<pre>@Content</pre>``` and also add ```white-space: inherit``` to the CSS for the ```<pre>```.
Anyway, I'll make those changes.

**Comment by conficient** [comment]
That's good thanks, I couldn't see how to get rid of the extra whitespace the `<pre>` introduced, hence the Cleanup method

**Pull request merged**
