### PR TITLE
Blazor preview6

### PR DESCRIPTION
**Pull request by conficient**
Updated BlazorBinding project for preview 6

### CODE REVIEW

**Comment by conficient** [comment]
Ah, just noticed the ValueBinding examples are not working

**Comment by conficient** [comment]
Fixed Value binding examples

**Comment by SQL-MisterMagoo** [comment]
Hi, thanks so much for submitting this, but - unfortunately it is based on a very old commit and there have been 36 commits since then that changed some of the fundamentals of the code.

I'll have a go at merging it manually to see if I can salvage anything, but it may be too much work because of this.

I really appreciate the work you've put into this and, if nothing else, it will server as a reminder that the code needs updating - I should definitely include some EventCallback examples - good and bad, and probably some Blazor-State/Blazor-Redux/Blazor-Fluxor examples too.

I'll keep this open and try to merge it - let's see what happens

**Comment by SQL-MisterMagoo** [comment]
Looks like it merged ok, which is very surprising!
I'll have this committed soon.

**Comment by SQL-MisterMagoo** [comment]
@conficient 
Thanks again - I had started moving it to preview3 ages ago but it was a lot of work, so I really appreciate the help.

**Comment by conficient** [comment]
No problem - was a good exercise in seeing all the changes

**Pull request merged**
